### ISSUE TITLE
Different paths for different hosts

### ISSUE THREAD

**Issue by jkoop** [lamyj/sneakersync#7]
Let's say I want to synchronise my home directory on two computers (`alfa`, and `bravo`), but my username (and therefore, the path of my home dir) are different.

Perhaps a `sneakersync.cfg` like this:
```
modules:
  - root:
    - alfa: /home/username
    - bravo: /home/something-else
```
And if I try to sync with a third computer (`charlie`), it should die with an error like so:
```
Error: hostname "charlie" not found in sneakersync.cfg
```
