### ISSUE TITLE
Host-specific include/exclude filters

### ISSUE THREAD

**Issue by jkoop** [lamyj/sneakersync#8]
( See issue #7 )

`sneakersync.cfg`:

```yaml
modules:
  - root:
    - alfa: /home/username
      filters:
        - exclude: /home/username/.cache
    - bravo: /home/something-else
```
